package com.example.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.data.CodeFileEntity
import com.example.data.CodeProjectEntity
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object ProjectZipUtil {

    /**
     * Zips project files into a .zip archive and returns the generated File
     */
    fun zipProject(context: Context, project: CodeProjectEntity, files: List<CodeFileEntity>): File {
        val exportDir = File(context.cacheDir, "exports")
        if (!exportDir.exists()) exportDir.mkdirs()

        val sanitizedName = project.name.replace("\\s+".toRegex(), "_").replace("[^a-zA-Z0-9_]".toRegex(), "")
        val zipFile = File(exportDir, "${sanitizedName}_backup.zip")
        if (zipFile.exists()) zipFile.delete()

        ZipOutputStream(FileOutputStream(zipFile)).use { zos ->
            // Add README
            val readmeContent = """
                # ${project.name}
                ${project.description}
                
                Generated and exported by Trill AI.
                Export Date: ${java.util.Date(project.updatedAt)}
                Total Files: ${files.size}
            """.trimIndent()

            val readmeEntry = ZipEntry("README.md")
            zos.putNextEntry(readmeEntry)
            zos.write(readmeContent.toByteArray())
            zos.closeEntry()

            // Add project manifest for cross-platform sync
            val syncJson = JSONObject().apply {
                put("projectName", project.name)
                put("description", project.description)
                put("createdAt", project.createdAt)
                put("updatedAt", project.updatedAt)
                put("version", "1.0")
                put("engine", "Trill AI")
                val filesArr = JSONArray()
                files.forEach { file ->
                    val fObj = JSONObject().apply {
                        put("filename", file.filename)
                        put("language", file.language)
                        put("content", file.content)
                    }
                    filesArr.put(fObj)
                }
                put("files", filesArr)
            }

            val manifestEntry = ZipEntry("trill_sync_manifest.json")
            zos.putNextEntry(manifestEntry)
            zos.write(syncJson.toString(2).toByteArray())
            zos.closeEntry()

            // Add each project file
            files.forEach { file ->
                val entry = ZipEntry("src/${file.filename}")
                zos.putNextEntry(entry)
                zos.write(file.content.toByteArray())
                zos.closeEntry()
            }
        }

        return zipFile
    }

    /**
     * Shares the generated zip file or text
     */
    fun shareZipFile(context: Context, zipFile: File, projectName: String) {
        val uri: Uri = try {
            FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                zipFile
            )
        } catch (_: Exception) {
            Uri.fromFile(zipFile)
        }

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "application/zip"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Trill AI Project Backup: $projectName")
            putExtra(Intent.EXTRA_TEXT, "Exported project $projectName from Trill AI.")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_ACTIVITY_NEW_TASK)
        }

        val chooser = Intent.createChooser(shareIntent, "Export $projectName ZIP Archive").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(chooser)
    }

    /**
     * Shares plain text query/response
     */
    fun shareText(context: Context, title: String, content: String) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, title)
            putExtra(Intent.EXTRA_TEXT, "$title\n\n$content\n\n-- Generated by Trill AI")
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        val chooser = Intent.createChooser(intent, "Share via").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        context.startActivity(chooser)
    }
}
